service: serverless-ping
package:
  patterns:
    - '!my-layers'
    - '!LICENSE'
    - '!readme.md'
    - '!requirements.txt'
  #  - '!vendord/**'
  #  - '!site-packages'
provider:
  name: aws
  region: us-east-2
  stage: dev
  runtime: python3.9
  memorySize: 128
  timeout: 1
  environment:
    SERVICE_STAGE: serverless-ping-HomeBase
    PING_METRIC_NAME: ${self:provider.environment.SERVICE_STAGE}
    PING_ALARM_NAMESPACE: ${opt:ping-alarm-namespace, 'Serverless/Ping'}
    PING_NAME: 'HomeBasele'
    PING_HOST: 'homebase.reznikcloud.com'
    PING_PORT: 40443
    PING_ALARM_EMAIL: 'rvadik@gmail.com'
    SENTRY_DSN: ''
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:PutMetricData
          Resource: "*"
layers:
  ping-layer:
    name: ${self:service}-${self:provider.stage}-layer
    description: 'Python requirements lambda layer'
    path: vendored/
    compatibleRuntimes:
      - python3.9
      - python3.8
      - python3.6
    allowedAccounts:
      - '*'

functions:
  ping_tester:
    handler: handler.pingtest
    
   # layers: 
   #   - arn:aws:lambda:us-east-2:528025216992:layer:serverless-ping-dev-layer:9

    events:
      - schedule: rate(1 minute)
resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:provider.environment.SERVICE_STAGE}
    SNSSubscription:
      Type: AWS::SNS::Subscription
      DependsOn: SNSTopic
      Properties:
        Protocol: email
        Endpoint: ${self:provider.environment.PING_ALARM_EMAIL}
        TopicArn:
          Ref: SNSTopic
    PingAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn: SNSSubscription
      Properties:
        AlarmName: ${self:provider.environment.PING_NAME}-alarm
        Namespace: ${self:provider.environment.PING_ALARM_NAMESPACE}
        MetricName: ${self:provider.environment.PING_METRIC_NAME}
        Dimensions:
          - Name: Host
            Value: ${self:provider.environment.PING_HOST}
        Statistic: Minimum
        Period: 60
        EvaluationPeriods: 1
        Threshold: 0
        ComparisonOperator: LessThanOrEqualToThreshold
        AlarmActions:
          - Ref: SNSTopic
        InsufficientDataActions:
          - Ref: SNSTopic
        OKActions:
          - Ref: SNSTopic
custom:
    noDeploy:
     - json
     - boto3
     - os
     - time
     - logging
